<?php
/** Daily AI analysis pipeline coordinator. PHP 5.6 / MySQL 5.6 compatible. */
namespace App\Services;

use App\Core\Db;
use App\Core\Auth;
use PDO;
use Exception;

require_once __DIR__ . '/AiDailySnapshotService.php';
require_once __DIR__ . '/AiInputCompletionPatternService.php';
require_once __DIR__ . '/AiCostForecastV2Service.php';
require_once __DIR__ . '/AiCostProjectionRiskService.php';
require_once __DIR__ . '/AiInputReliabilityService.php';
require_once __DIR__ . '/AiAnomalyDetectionService.php';
require_once __DIR__ . '/AiProfitRiskService.php';
require_once __DIR__ . '/AiCeoIndexService.php';
require_once __DIR__ . '/AiExecutiveBriefService.php';
require_once __DIR__ . '/AiCostDataGovernanceService.php';
require_once __DIR__ . '/AiProjectTypeService.php';
require_once __DIR__ . '/AiForecastAccuracyService.php';
require_once __DIR__ . '/AiMemoryService.php';

class AiDailyPipelineService
{
    const RUN_TABLE='cpms_ai_pipeline_runs';
    const STEP_TABLE='cpms_ai_pipeline_steps';
    private static $tableCache=array();

    public static function pdo($pdo=null){return $pdo?$pdo:Db::pdo();}
    private static function key($pdo){return is_object($pdo)?spl_object_hash($pdo):'none';}
    public static function tableExists($pdo,$table){if(!$pdo||!preg_match('/^[A-Za-z0-9_]+$/',(string)$table))return false;$key=self::key($pdo).':'.$table;if(array_key_exists($key,self::$tableCache))return self::$tableCache[$key];try{$st=$pdo->prepare('SHOW TABLES LIKE :table');$ok=$st&&$st->execute(array(':table'=>$table))&&$st->fetchColumn()!==false;self::$tableCache[$key]=$ok;return $ok;}catch(Exception $e){return false;}}
    public static function createRunTableSql(){return "CREATE TABLE IF NOT EXISTS cpms_ai_pipeline_runs (\n id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,\n run_uid VARCHAR(64) NOT NULL,\n run_date DATE NOT NULL,\n target_ym CHAR(7) NOT NULL,\n trigger_type VARCHAR(20) NOT NULL,\n run_status VARCHAR(20) NOT NULL,\n last_success_step VARCHAR(50) NULL,\n failed_step VARCHAR(50) NULL,\n source_fingerprint CHAR(64) NULL,\n force_run TINYINT(1) NOT NULL DEFAULT 0,\n actor_employee_id INT NULL,\n actor_name VARCHAR(100) NULL,\n started_at DATETIME NOT NULL,\n finished_at DATETIME NULL,\n error_summary VARCHAR(500) NULL,\n created_at DATETIME NOT NULL,\n UNIQUE KEY uk_ai_pipeline_run_uid (run_uid),\n KEY idx_ai_pipeline_date (run_date,started_at),\n KEY idx_ai_pipeline_status (run_status,started_at)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";}
    public static function createStepTableSql(){return "CREATE TABLE IF NOT EXISTS cpms_ai_pipeline_steps (\n id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,\n run_id BIGINT UNSIGNED NOT NULL,\n step_name VARCHAR(50) NOT NULL,\n step_order INT UNSIGNED NOT NULL,\n step_status VARCHAR(20) NOT NULL,\n processed_count INT UNSIGNED NOT NULL DEFAULT 0,\n success_count INT UNSIGNED NOT NULL DEFAULT 0,\n failure_count INT UNSIGNED NOT NULL DEFAULT 0,\n started_at DATETIME NOT NULL,\n finished_at DATETIME NULL,\n safe_message VARCHAR(500) NULL,\n created_at DATETIME NOT NULL,\n KEY idx_ai_pipeline_step_run (run_id,step_order),\n KEY idx_ai_pipeline_step_status (step_status,started_at)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";}
    public static function installOrUpdate($pdo=null){$pdo=self::pdo($pdo);if(!$pdo)return array('ok'=>false,'message'=>'DB 연결 상태를 확인할 수 없습니다.');$messages=array();try{foreach(array(self::createRunTableSql(),self::createStepTableSql()) as $sql)if($pdo->exec($sql)===false)throw new Exception('schema');self::$tableCache=array();$results=array(AiCostDataGovernanceService::installOrUpdate($pdo),AiProjectTypeService::installOrUpdate($pdo),AiInputCompletionPatternService::installOrUpdate($pdo),AiCostForecastV2Service::installOrUpdate($pdo),AiForecastAccuracyService::installOrUpdate($pdo),AiMemoryService::installOrUpdate($pdo),AiCeoIndexService::installV2($pdo));$ok=self::isInstalled($pdo);foreach($results as $result){if(empty($result['ok']))$ok=false;if(isset($result['message']))$messages[]=$result['message'];}return array('ok'=>$ok,'message'=>($ok?'파이프라인 전용 테이블 설치를 확인했습니다. ':'파이프라인 설치상태를 확인해주세요. ').implode(' ',$messages));}catch(Exception $e){error_log('[AI Pipeline] install failed: '.$e->getMessage());return array('ok'=>false,'message'=>'파이프라인 테이블 설치를 확인하지 못했습니다.');}}
    public static function isInstalled($pdo=null){$pdo=self::pdo($pdo);return $pdo&&self::tableExists($pdo,self::RUN_TABLE)&&self::tableExists($pdo,self::STEP_TABLE)&&AiCostDataGovernanceService::isInstalled($pdo)&&AiProjectTypeService::isInstalled($pdo)&&AiInputCompletionPatternService::isInstalled($pdo)&&AiCostForecastV2Service::isInstalled($pdo)&&AiForecastAccuracyService::isInstalled($pdo)&&AiMemoryService::isInstalled($pdo)&&AiCeoIndexService::isV2Installed($pdo);}
    public static function schemaStatus($pdo=null){$pdo=self::pdo($pdo);$s=array('db_available'=>(bool)$pdo,'installed'=>false,'latest_run'=>array(),'run_count'=>0,'settings'=>array('min_completion_rate'=>20));if(!$pdo)return $s;$s['installed']=self::isInstalled($pdo);$s['settings']=array('min_completion_rate'=>AiInputCompletionPatternService::minCompletionRate($pdo));if(!self::tableExists($pdo,self::RUN_TABLE))return $s;try{$st=$pdo->query('SELECT * FROM `'.self::RUN_TABLE.'` ORDER BY started_at DESC,id DESC LIMIT 1');$row=$st?$st->fetch(PDO::FETCH_ASSOC):false;$s['latest_run']=is_array($row)?$row:array();$st=$pdo->query('SELECT COUNT(*) FROM `'.self::RUN_TABLE.'`');$s['run_count']=$st?(int)$st->fetchColumn():0;}catch(Exception $e){}return $s;}
    private static function actor($trigger){if($trigger==='SYSTEM'||$trigger==='CLI')return array('id'=>null,'name'=>null);$u=Auth::user();$name=isset($u['name'])?(string)$u['name']:'';$name=function_exists('mb_substr')?mb_substr($name,0,100,'UTF-8'):substr($name,0,100);return array('id'=>isset($u['employee_id'])?(int)$u['employee_id']:null,'name'=>$name!==''?$name:null);}
    private static function acquireLock($pdo,$date){$name='cpms_ai_daily_pipeline_'.str_replace('-','',$date);try{$st=$pdo->prepare('SELECT GET_LOCK(:name,0)');if(!$st||!$st->execute(array(':name'=>$name)))return array('ok'=>true,'name'=>'');return array('ok'=>(int)$st->fetchColumn()===1,'name'=>$name);}catch(Exception $e){return array('ok'=>true,'name'=>'');}}
    private static function releaseLock($pdo,$lock){if(empty($lock['name']))return;try{$st=$pdo->prepare('SELECT RELEASE_LOCK(:name)');if($st)$st->execute(array(':name'=>$lock['name']));}catch(Exception $e){}}
    private static function successfulToday($pdo,$date){try{$st=$pdo->prepare("SELECT id FROM `".self::RUN_TABLE."` WHERE run_date=:date AND run_status='SUCCESS' ORDER BY id DESC LIMIT 1");return $st&&$st->execute(array(':date'=>$date))&&$st->fetchColumn()!==false;}catch(Exception $e){return false;}}
    private static function createRun($pdo,$date,$ym,$trigger,$force){$actor=self::actor($trigger);$uid=hash('sha256',uniqid('',true).microtime(true).mt_rand());$now=date('Y-m-d H:i:s');$st=$pdo->prepare('INSERT INTO `'.self::RUN_TABLE.'` (run_uid,run_date,target_ym,trigger_type,run_status,force_run,actor_employee_id,actor_name,started_at,created_at) VALUES (:uid,:date,:ym,:trigger,\'RUNNING\',:force,:actor_id,:actor_name,:started,:created)');if(!$st||!$st->execute(array(':uid'=>$uid,':date'=>$date,':ym'=>$ym,':trigger'=>$trigger,':force'=>$force?1:0,':actor_id'=>$actor['id'],':actor_name'=>$actor['name'],':started'=>$now,':created'=>$now)))return 0;return (int)$pdo->lastInsertId();}
    private static function startStep($pdo,$runId,$name,$order){$now=date('Y-m-d H:i:s');$st=$pdo->prepare('INSERT INTO `'.self::STEP_TABLE.'` (run_id,step_name,step_order,step_status,started_at,created_at) VALUES (:run,:name,:step_order,\'RUNNING\',:started,:created)');if(!$st||!$st->execute(array(':run'=>$runId,':name'=>$name,':step_order'=>$order,':started'=>$now,':created'=>$now)))return 0;return (int)$pdo->lastInsertId();}
    private static function finishStep($pdo,$stepId,$status,$result,$message){$processed=isset($result['projects'])?(int)$result['projects']:(isset($result['patterns'])?(int)$result['patterns']:0);$success=isset($result['success'])?(int)$result['success']:(empty($result['ok'])?0:$processed);$failure=isset($result['failed'])?(int)$result['failed']:(empty($result['ok'])?max(1,$processed):0);$st=$pdo->prepare('UPDATE `'.self::STEP_TABLE.'` SET step_status=:status,processed_count=:processed,success_count=:success,failure_count=:failure,finished_at=:finished,safe_message=:message WHERE id=:id');if($st)$st->execute(array(':status'=>$status,':processed'=>$processed,':success'=>$success,':failure'=>$failure,':finished'=>date('Y-m-d H:i:s'),':message'=>substr(str_replace(array("\r","\n"),' ',(string)$message),0,500),':id'=>$stepId));}
    private static function finishRun($pdo,$runId,$status,$lastSuccess,$failedStep,$fingerprint,$message){$st=$pdo->prepare('UPDATE `'.self::RUN_TABLE.'` SET run_status=:status,last_success_step=:last_success,failed_step=:failed_step,source_fingerprint=:fingerprint,finished_at=:finished,error_summary=:message WHERE id=:id');if($st)$st->execute(array(':status'=>$status,':last_success'=>$lastSuccess!==''?$lastSuccess:null,':failed_step'=>$failedStep!==''?$failedStep:null,':fingerprint'=>$fingerprint!==''?$fingerprint:null,':finished'=>date('Y-m-d H:i:s'),':message'=>$message!==''?substr($message,0,500):null,':id'=>$runId));}
    private static function stepStatus($result,$optional){if(!is_array($result)||empty($result['ok']))return $optional?'PARTIAL':'FAILED';$status=isset($result['status'])?strtoupper((string)$result['status']):'COMPLETED';return in_array($status,array('FAILED'),true)?($optional?'PARTIAL':'FAILED'):(in_array($status,array('PARTIAL'),true)?'PARTIAL':'SUCCESS');}

    public static function run($pdo=null,$triggerType='SYSTEM',$force=false)
    {
        $pdo=self::pdo($pdo);$empty=array('ok'=>false,'status'=>'FAILED','message'=>'자동 분석 파이프라인을 실행하지 못했습니다.','steps'=>array());if(!$pdo){$empty['message']='DB 연결 상태를 확인할 수 없습니다.';return $empty;}if(!self::isInstalled($pdo)){$empty['message']='자동 분석 파이프라인 테이블을 먼저 설치해주세요.';return $empty;}$date=CostChangeService::businessToday();$ym=CostChangeService::currentSettlementYm('labor',$date);$trigger=in_array(strtoupper((string)$triggerType),array('MANUAL','CLI','SYSTEM'),true)?strtoupper((string)$triggerType):'SYSTEM';if(!$force&&self::successfulToday($pdo,$date))return array('ok'=>true,'status'=>'SKIPPED','message'=>'오늘 자동 분석이 이미 완료되었습니다.','steps'=>array());$lock=self::acquireLock($pdo,$date);if(empty($lock['ok'])){$empty['message']='자동 분석 파이프라인이 이미 실행 중입니다.';return $empty;}$runId=self::createRun($pdo,$date,$ym,$trigger,$force);if($runId<=0){self::releaseLock($pdo,$lock);return $empty;}
        $steps=array(
            array('snapshot',false,array('App\\Services\\AiDailySnapshotService','captureToday'),array($pdo,$trigger)),
            array('input_pattern',false,array('App\\Services\\AiInputCompletionPatternService','calculateLatest'),array($pdo,$trigger)),
            array('forecast_v2',false,array('App\\Services\\AiCostForecastV2Service','forecastLatest'),array($pdo,$trigger)),
            array('actual_close',true,array('App\\Services\\AiForecastAccuracyService','captureClosedActuals'),array($pdo,$date,'일일 파이프라인 정상 마감 집계')),
            array('forecast_accuracy',true,array('App\\Services\\AiForecastAccuracyService','evaluate'),array($pdo)),
            array('reliability',true,array('App\\Services\\AiInputReliabilityService','calculateLatest'),array($pdo,$trigger)),
            array('anomaly',true,array('App\\Services\\AiAnomalyDetectionService','detectLatest'),array($pdo,$trigger)),
            array('projection_risk',false,array('App\\Services\\AiCostProjectionRiskService','analyzeLatest'),array($pdo,$trigger)),
            array('profit_risk',true,array('App\\Services\\AiProfitRiskService','analyzeLatest'),array($pdo,$trigger)),
            array('ceo_index_v2',false,array('App\\Services\\AiCeoIndexService','calculateLatestV2'),array($pdo,$trigger)),
            array('gpt_summary',true,array('App\\Services\\AiExecutiveBriefService','generateLatest'),array($pdo,$trigger,$force))
        );
        $overall='SUCCESS';$lastSuccess='';$failedStep='';$safeMessage='';$results=array();
        try{foreach($steps as $index=>$definition){$name=$definition[0];$optional=$definition[1];$stepId=self::startStep($pdo,$runId,$name,$index+1);$result=array();try{$result=call_user_func_array($definition[2],$definition[3]);if(!is_array($result))$result=array('ok'=>false,'message'=>'단계 응답을 확인할 수 없습니다.');}catch(Exception $e){$result=array('ok'=>false,'message'=>'단계 실행 중 오류가 발생했습니다.');error_log('[AI Pipeline] step failed: '.$name);}$status=self::stepStatus($result,$optional);$message=isset($result['message'])?(string)$result['message']:$status;self::finishStep($pdo,$stepId,$status,$result,$message);$results[$name]=array('status'=>$status,'message'=>$message);if($status==='SUCCESS')$lastSuccess=$name;else{$overall=$overall==='FAILED'?'FAILED':'PARTIAL';if($failedStep==='')$failedStep=$name;$safeMessage=$message;if(!$optional){$overall='FAILED';break;}}}$fingerprint=hash('sha256',json_encode(array('date'=>$date,'ym'=>$ym,'steps'=>$results),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));self::finishRun($pdo,$runId,$overall,$lastSuccess,$failedStep,$fingerprint,$safeMessage);self::releaseLock($pdo,$lock);return array('ok'=>$overall!=='FAILED','status'=>$overall,'message'=>$overall==='SUCCESS'?'자동 분석 파이프라인을 완료했습니다.':($overall==='PARTIAL'?'일부 단계가 제한된 상태로 완료되었습니다.':'자동 분석 핵심단계가 중단되었습니다.'),'steps'=>$results,'run_id'=>$runId);}catch(Exception $e){self::finishRun($pdo,$runId,'FAILED',$lastSuccess,$failedStep,'','파이프라인 실행 중 오류가 발생했습니다.');self::releaseLock($pdo,$lock);error_log('[AI Pipeline] run failed');return $empty;}
    }
    public static function listRuns($pdo,$page,$perPage){$pdo=self::pdo($pdo);$page=max(1,(int)$page);$perPage=max(1,min(100,(int)$perPage));if(!$pdo||!self::tableExists($pdo,self::RUN_TABLE))return array();try{$st=$pdo->prepare('SELECT * FROM `'.self::RUN_TABLE.'` ORDER BY started_at DESC,id DESC LIMIT :limit OFFSET :offset');if(!$st)return array();$st->bindValue(':limit',$perPage,PDO::PARAM_INT);$st->bindValue(':offset',($page-1)*$perPage,PDO::PARAM_INT);if(!$st->execute())return array();$rows=$st->fetchAll(PDO::FETCH_ASSOC);return is_array($rows)?$rows:array();}catch(Exception $e){return array();}}
    public static function countRuns($pdo){$pdo=self::pdo($pdo);if(!$pdo||!self::tableExists($pdo,self::RUN_TABLE))return 0;try{$st=$pdo->query('SELECT COUNT(*) FROM `'.self::RUN_TABLE.'`');return $st?(int)$st->fetchColumn():0;}catch(Exception $e){return 0;}}
    public static function stepsForRun($pdo,$runId){$pdo=self::pdo($pdo);if(!$pdo||!self::tableExists($pdo,self::STEP_TABLE))return array();try{$st=$pdo->prepare('SELECT * FROM `'.self::STEP_TABLE.'` WHERE run_id=:run ORDER BY step_order,id');if(!$st||!$st->execute(array(':run'=>(int)$runId)))return array();$rows=$st->fetchAll(PDO::FETCH_ASSOC);return is_array($rows)?$rows:array();}catch(Exception $e){return array();}}
}
?>
