<?php
use App\Core\Db; require_once __DIR__.'/_common.php';
$pdo=Db::pdo(); $id=isset($_GET['id'])?(int)$_GET['id']:0; $u=\App\Core\Auth::user();
$st=$pdo->prepare("SELECT * FROM cpms_approval_documents WHERE id=:id LIMIT 1"); $st->execute(array(':id'=>$id)); $d=$st->fetch();
$st=$pdo->prepare("SELECT * FROM cpms_approval_lines WHERE document_id=:id ORDER BY line_order"); $st->execute(array(':id'=>$id)); $lines=$st->fetchAll();
$st=$pdo->prepare("SELECT * FROM cpms_approval_files WHERE document_id=:id ORDER BY id DESC"); $st->execute(array(':id'=>$id)); $files=$st->fetchAll();
$content=approval_parse_content($d['content']); $canCancel=((int)$d['created_by_id']===(int)$u['id'] && in_array($d['doc_status'],array('PENDING','DRAFT')));
?><div class="space-y-4"><div class="flex gap-2"><a href="?r=approval_home" class="px-3 py-2 bg-gray-100 rounded-xl">목록으로</a><a href="?r=approval_print&id=<?php echo $id;?>" class="px-3 py-2 bg-indigo-100 rounded-xl">출력</a><?php if($canCancel){?><form method="post" action="?r=approval_cancel"><input type="hidden" name="_csrf" value="<?php echo h(csrf_token());?>"><input type="hidden" name="id" value="<?php echo $id;?>"><button class="px-3 py-2 bg-rose-100 rounded-xl">요청취소</button></form><?php } ?></div>
<div class="bg-white rounded-3xl border p-6"><h2 class="text-2xl font-extrabold"><?php echo h($d['title']);?></h2><div class="mt-2">문서종류: <?php echo h(approval_doc_label($d['doc_type']));?> / 상태: <span class="px-2 py-1 rounded-full border <?php echo approval_status_badge($d['doc_status']);?>"><?php echo h($d['doc_status']);?></span></div></div>
<?php if($d['doc_status']==='REJECTED'){?><div class="bg-rose-50 border border-rose-200 rounded-2xl p-4">반려단계: <?php echo h($d['rejected_step']);?> / 반려사유: <?php echo h($d['reject_reason']);?></div><?php } ?>
<div class="bg-white rounded-3xl border p-6"><h3 class="font-bold mb-2">결재라인</h3><table class="w-full text-sm"><tr><th>역할</th><th>결재자</th><th>상태</th><th>승인일시</th><th>사인</th></tr><?php foreach($lines as $l){$sig=trim((string)$l['sign_path']);$abs=dirname(__DIR__,3).'/'.$sig;?><tr><td><?php echo h($l['role_type']);?></td><td><?php echo h($l['approver_name']);?></td><td><?php echo h($l['line_status']);?></td><td><?php echo h($l['acted_at']);?></td><td><?php if($l['line_status']==='APPROVED' && $sig!=='' && is_file($abs)){?><img src="../<?php echo h($sig);?>" style="height:40px;"><?php } else { echo '사인 미등록'; } ?></td></tr><?php if($l['line_status']==='REJECTED'){?><tr><td></td><td colspan="4" class="text-rose-700">반려사유: <?php echo h($l['reject_reason']);?></td></tr><?php }}?></table></div>
</div>