<?php
// tests/cpms2_historical_project_test.php
// PHP 5.6, in-memory synthetic rows only; no operational connection.
require_once __DIR__.'/cpms2_reference_closure_test.php';
$checks=0;
$db->exec('PRAGMA query_only=OFF');
$db->exec("DELETE FROM cpms_equipment_usage WHERE id=202;
DELETE FROM cpms_projects WHERE id=8;
CREATE TABLE cpms_ai_daily_snapshots(id INTEGER PRIMARY KEY,project_id INTEGER,project_name_snapshot TEXT,project_status_snapshot TEXT,project_start_date TEXT,project_end_date TEXT,contract_amount TEXT,snapshot_date TEXT,captured_at TEXT);
CREATE TABLE cpms_cost_data_events(id INTEGER PRIMARY KEY,project_id INTEGER,project_name_snapshot TEXT,event_at TEXT,actual_date TEXT);
INSERT INTO cpms_ai_daily_snapshots VALUES(1,8,'  Historical   Project  ','진행중','2020-01-01','2020-12-31','1000000.00','2020-02-01','2020-02-01 12:00:00'),(2,8,'Historical Project','정산완료','2020-01-01','2020-12-31','1200000.00','2020-12-31','2020-12-31 12:00:00'),(3,9,'Unreferenced deleted project','진행중',NULL,NULL,NULL,'2020-12-31','2020-12-31 12:00:00');
INSERT INTO cpms_cost_data_events VALUES(1,8,'Historical Project','2021-01-01 12:00:00','2020-12-31');");
$db->exec('PRAGMA query_only=ON');
$service=new Cpms2HistoricalProjectRecoveryService($source); $result=$service->recover(8); $row=$result['row'];
referenceAssert($row['name']==='Historical Project' && $row['recovery_source']==='ai_daily_snapshot','AI source priority or normalized name failed.');
referenceAssert($row['status']==='정산완료' && $row['contract_amount']==='1200000.00' && $row['source_snapshot_date']==='2020-12-31','Latest factual snapshot selection failed.');
referenceAssert($row['start_date']==='2020-01-01' && $row['end_date']==='2020-12-31' && $row['client']===null && $row['contractor']===null && $row['location']===null,'Unobserved project fields invented.');
referenceAssert($row['legacy_project_physically_deleted']===1 && $result['diagnostic']['status_confirmed'],'Recovery provenance missing.');
$closure=new Cpms2ReferencedMasterClosure($source); $report=$closure->summary();
referenceAssert(!$closure->failures() && $report['projects']['physically_missing']===0 && $report['projects']['historical_snapshot_recovered']===1 && $report['projects']['reference_recovered']===1,'Physical missing project not closed.');
$projects=iterator_to_array($closure->rows('cpms_projects',array('id','name','status')),false);
referenceAssert(count($projects)===2 && $projects[1]['id']==8 && $projects[1]['recovered_by']==='historical_project_snapshot','Duplicate or unreferenced synthetic projects exported.');
$filtered=iterator_to_array($closure->rows('cpms_projects',array('id','name')),false);
referenceAssert(!isset($filtered[1]['status']) && $filtered[1]['legacy_project_physically_deleted']===1,'Historical rows did not honor field whitelist.');
referenceAssert($projects[0]['id']==1 && $projects[0]['name']==='current','Normal project changed.');
$db->exec('PRAGMA query_only=OFF'); $db->exec('DELETE FROM cpms_ai_daily_snapshots WHERE project_id=8'); $db->exec('PRAGMA query_only=ON');
$row=$service->recover(8)['row'];
referenceAssert($row['recovery_source']==='cost_data_event' && $row['name']==='Historical Project' && $row['status']===null && $row['contract_amount']===null && $row['start_date']===null,'Event-only recovery guessed unknown fields.');
$db->exec('PRAGMA query_only=OFF'); $db->exec("INSERT INTO cpms_cost_data_events VALUES(2,8,'Conflicting name','2021-02-01 12:00:00',NULL)"); $db->exec('PRAGMA query_only=ON');
$failure=$service->recover(8); referenceAssert($failure['row']===null && $failure['diagnostic']['code']==='legacy_project_snapshot_ambiguous','Conflicting names were arbitrarily chosen.');
$closure=new Cpms2ReferencedMasterClosure($source);
referenceAssert($closure->failures()[0]['code']==='legacy_project_snapshot_ambiguous','Snapshot conflict not blocking closure.');
$db->exec('PRAGMA query_only=OFF'); $db->exec("DELETE FROM cpms_cost_data_events WHERE project_id=8; INSERT INTO cpms_cost_data_events VALUES(3,8,'   ',NULL,NULL)"); $db->exec('PRAGMA query_only=ON');
$failure=$service->recover(8); referenceAssert($failure['row']===null && $failure['diagnostic']['code']==='legacy_project_snapshot_unavailable','Empty snapshot produced a fake project.');
$closure=new Cpms2ReferencedMasterClosure($source);
referenceAssert($closure->summary()['projects']['physically_missing']===1 && $closure->failures()[0]['code']==='legacy_project_snapshot_unavailable','Unavailable project did not block.');
$diagnostic=Cpms2ExportFailure::safe('projects',new RuntimeException('legacy_project_snapshot_ambiguous'));
referenceAssert($diagnostic->getMessage()==='legacy_project_snapshot_ambiguous','Safe snapshot diagnostic lost.');
referenceAssert($db->query('SELECT COUNT(*) FROM cpms_projects')->fetchColumn()==2,'Recovery wrote a project master.');
$db->exec('PRAGMA query_only=OFF');
$db->exec("INSERT INTO cpms_ai_daily_snapshots VALUES(100,8,'Historical Project',NULL,NULL,NULL,NULL,'2020-12-31',NULL);
INSERT INTO cpms_material_items VALUES(14,8,1,'자재비','second reference',1); INSERT INTO cpms_material_usage VALUES(103,8,14,0);
UPDATE workers SET is_deleted=0 WHERE id=21; INSERT INTO workers VALUES(1475,'Referenced historical worker',1);
INSERT INTO cpms_project_labor_workers VALUES(405,8,NULL,NULL,'snapshot A',NULL,0),(406,8,NULL,NULL,'snapshot B',NULL,0),(407,8,NULL,NULL,'snapshot C',NULL,0);");
for ($i=40;$i<70;$i++) { $db->exec("INSERT INTO cpms_equipment_items VALUES($i,8,1,'장비','reference fixture',1)"); $db->exec('INSERT INTO cpms_equipment_usage VALUES('.($i+600).',8,'.$i.',0)'); }
$db->exec('PRAGMA query_only=ON'); $closure=new Cpms2ReferencedMasterClosure($source); $report=$closure->summary();
referenceAssert(!$closure->failures() && $report['projects']['historical_snapshot_recovered']===1 && $report['projects']['physically_missing']===0,'Historical project exact-count closure failed.');
referenceAssert($report['material_items']['reference_recovered']===2 && $report['equipment_items']['reference_recovered']===31 && $report['workers']['reference_recovered']===1 && $report['workers']['snapshot_only_labor_workers']===4 && $report['workers']['physically_missing']===0,'Operational reference recovery cardinalities regressed.');
$db->exec('PRAGMA query_only=OFF');
$db->exec("DROP TABLE cpms_ai_daily_snapshots; CREATE TABLE cpms_ai_daily_snapshots(project_id INTEGER,project_name_snapshot TEXT,project_status_snapshot TEXT);
INSERT INTO cpms_ai_daily_snapshots VALUES(8,'Historical Project','진행중'),(8,'Historical Project','정산완료');");
$db->exec('PRAGMA query_only=ON'); $row=$service->recover(8)['row'];
referenceAssert($row['status']===null && !isset($row['source_status_snapshot']),'Undated conflicting status was guessed.');
$db->exec('PRAGMA query_only=OFF'); $db->exec('DELETE FROM cpms_ai_daily_snapshots');
$insert=$db->prepare('INSERT INTO cpms_ai_daily_snapshots VALUES(8,?,NULL)');
for ($i=0;$i<501;$i++) $insert->execute(array($i===500?'Late conflicting name':'Historical Project'));
$db->exec('PRAGMA query_only=ON');
referenceAssert($service->recover(8)['diagnostic']['code']==='legacy_project_snapshot_ambiguous','Conflict beyond the first 500 rows was missed.');
echo 'PASS: '.$checks." historical project recovery / conflict / unknown / READ ONLY checks\n";
