<?php
/** AI cost-origin and project-type governance. PHP 5.6 compatible. */
use App\Core\Auth;
use App\Core\Db;
use App\Services\CostDataEventService;
use App\Services\AiCostDataGovernanceService;
use App\Services\AiProjectTypeService;
use App\Services\AiDailyPipelineService;

require_once __DIR__ . '/../../services/CostDataEventService.php';
require_once __DIR__ . '/../../services/AiCostDataGovernanceService.php';
require_once __DIR__ . '/../../services/AiProjectTypeService.php';
require_once __DIR__ . '/../../services/AiDailyPipelineService.php';

if (!Auth::check() || !Auth::isDevelopmentDepartment()) { http_response_code(403); echo h('접근 권한이 없습니다.'); return; }
$govPdo=null;$govResult=null;try{$govPdo=Db::pdo();}catch(Exception $e){$govResult=array('ok'=>false,'message'=>'DB 연결 상태를 확인할 수 없습니다.');}
if($_SERVER['REQUEST_METHOD']==='POST'){
    $token=isset($_POST['_csrf'])?(string)$_POST['_csrf']:'';$action=isset($_POST['action'])?trim((string)$_POST['action']):'';
    if(!csrf_check($token))$govResult=array('ok'=>false,'message'=>'보안 토큰이 올바르지 않습니다.');
    else if(!$govPdo)$govResult=array('ok'=>false,'message'=>'DB 연결 상태를 확인할 수 없습니다.');
    else if($action==='install'){$a=CostDataEventService::installOrUpdate($govPdo);$b=AiDailyPipelineService::installOrUpdate($govPdo);$govResult=array('ok'=>!empty($a['ok'])&&!empty($b['ok']),'message'=>(isset($a['message'])?$a['message']:'').' '.(isset($b['message'])?$b['message']:''));}
    else if($action==='classify_existing')$govResult=AiCostDataGovernanceService::classifyExisting($govPdo);
    else if($action==='review_origin')$govResult=AiCostDataGovernanceService::reviewOrigin($govPdo,isset($_POST['map_id'])?(int)$_POST['map_id']:0,isset($_POST['data_origin'])?$_POST['data_origin']:'UNKNOWN_REVIEW',!empty($_POST['amount_eligible']),!empty($_POST['timing_eligible']),isset($_POST['reason'])?$_POST['reason']:'');
    else if($action==='save_type')$govResult=AiProjectTypeService::saveType($govPdo,$_POST,isset($_POST['reason'])?$_POST['reason']:'');
    else if($action==='assign_project')$govResult=AiProjectTypeService::assignProject($govPdo,isset($_POST['project_id'])?(int)$_POST['project_id']:0,isset($_POST['project_type_id'])?(int)$_POST['project_type_id']:0,isset($_POST['reason'])?$_POST['reason']:'');
    else $govResult=array('ok'=>false,'message'=>'요청값이 올바르지 않습니다.');
}
$govStatus=$govPdo?AiCostDataGovernanceService::status($govPdo):array('total_count'=>0,'unknown_count'=>0,'timing_eligible_count'=>0);$govSchema=$govPdo?AiCostDataGovernanceService::isInstalled($govPdo):false;$govRows=$govSchema?AiCostDataGovernanceService::listMappings($govPdo,array('origin'=>isset($_GET['origin'])?$_GET['origin']:''),1,100):array();$govTypes=$govPdo?AiProjectTypeService::listTypes($govPdo,false):array();$govProjects=array();
if($govPdo){try{$st=$govPdo->query('SELECT id,name FROM cpms_projects ORDER BY name,id LIMIT 1000');if($st){$rows=$st->fetchAll(PDO::FETCH_ASSOC);if(is_array($rows))$govProjects=$rows;}}catch(Exception $e){$govProjects=array();}}
$govOriginLabels=AiCostDataGovernanceService::originLabels();
?>
<style>
.gov{color:#0f172a}.gov *{box-sizing:border-box}.gov-card{background:#fff;border:1px solid #e2e8f0;border-radius:18px;padding:20px;margin:14px 0;box-shadow:0 7px 22px rgba(15,23,42,.05)}.gov h2,.gov h3{margin:0 0 10px}.gov-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.gov-stat{padding:14px;border-radius:13px;background:#f8fafc}.gov-stat small{display:block;color:#64748b}.gov-stat strong{font-size:20px}.gov-form{display:flex;gap:8px;align-items:end;flex-wrap:wrap}.gov-form label{display:grid;gap:5px;font-size:12px;font-weight:800}.gov input,.gov select,.gov textarea{border:1px solid #cbd5e1;border-radius:9px;padding:9px;background:#fff}.gov button,.gov-btn{border:0;border-radius:9px;padding:10px 13px;background:#1d4ed8;color:#fff;font-weight:900;cursor:pointer;text-decoration:none}.gov button.secondary{background:#475569}.gov-msg{padding:12px;border-radius:10px;background:#ecfdf5;color:#047857}.gov-msg.bad{background:#fef2f2;color:#b91c1c}.gov-table{width:100%;min-width:1250px;border-collapse:collapse}.gov-table th,.gov-table td{border:1px solid #e2e8f0;padding:8px;vertical-align:top}.gov-scroll{overflow:auto}.gov-note{color:#64748b;font-size:13px;line-height:1.6}@media(max-width:800px){.gov-grid{grid-template-columns:1fr 1fr}.gov-form>*{width:100%}.gov-form input,.gov-form select,.gov-form textarea,.gov-form button{width:100%}}
</style>
<div class="gov">
 <section class="gov-card"><h2>AI 데이터 원천·현장유형 관리</h2><p class="gov-note">기존 비용 원본은 수정하지 않습니다. 과거자료는 금액패턴에 사용할 수 있지만 실제 입력시점 학습에서는 제외하며, 원천 확인이 필요한 자료도 입력시점 학습에 포함하지 않습니다.</p>
 <?php if(is_array($govResult)): ?><div class="gov-msg <?php echo empty($govResult['ok'])?'bad':''; ?>"><?php echo h(isset($govResult['message'])?$govResult['message']:'처리 결과를 확인해주세요.'); ?></div><?php endif; ?>
 <div class="gov-form" style="margin-top:12px"><form method="post"><input type="hidden" name="_csrf" value="<?php echo h(csrf_token()); ?>"><input type="hidden" name="action" value="install"><button>설치/구조 확인</button></form><form method="post" onsubmit="return confirm('기존 원본은 변경하지 않고 아직 미분류인 자료의 원천 매핑을 생성합니다. 계속할까요?');"><input type="hidden" name="_csrf" value="<?php echo h(csrf_token()); ?>"><input type="hidden" name="action" value="classify_existing"><button class="secondary">기존자료 초기 분류</button></form><a class="gov-btn" href="?r=admin%2Fai_forecast_accuracy">예측 정확도</a></div></section>
 <section class="gov-grid"><div class="gov-stat"><small>원천 구조</small><strong><?php echo $govSchema?'설치 완료':'미설치'; ?></strong></div><div class="gov-stat"><small>분류 자료</small><strong><?php echo number_format((int)$govStatus['total_count']); ?>건</strong></div><div class="gov-stat"><small>원천 확인 필요</small><strong><?php echo number_format((int)$govStatus['unknown_count']); ?>건</strong></div><div class="gov-stat"><small>입력시점 사용 가능</small><strong><?php echo number_format((int)$govStatus['timing_eligible_count']); ?>건</strong></div></section>
 <section class="gov-card"><h3>현장유형 관리</h3><p class="gov-note">예시 유형을 자동 생성하거나 기존 현장에 임의 지정하지 않습니다. 미지정 현장은 유사 현장 비교자료 부족으로 처리됩니다.</p>
  <form method="post" class="gov-form"><input type="hidden" name="_csrf" value="<?php echo h(csrf_token()); ?>"><input type="hidden" name="action" value="save_type"><label>유형 코드<input name="type_code" required maxlength="60"></label><label>유형명<input name="type_name" required maxlength="120"></label><label>설명<input name="description" maxlength="500"></label><label>정렬순서<input type="number" name="sort_order" value="100"></label><label><span>활성</span><input type="checkbox" name="is_active" value="1" checked></label><label>변경사유<input name="reason" maxlength="500" value="신규 현장유형 등록"></label><button>현장유형 저장</button></form>
  <div class="gov-scroll"><table class="gov-table" style="min-width:850px;margin-top:12px"><thead><tr><th>코드</th><th>현장유형명</th><th>설명</th><th>상태</th><th>수정</th></tr></thead><tbody><?php if(count($govTypes)===0): ?><tr><td colspan="5">등록된 현장유형이 없습니다.</td></tr><?php else:foreach($govTypes as $type): ?><tr><td><?php echo h($type['type_code']); ?></td><td><?php echo h($type['type_name']); ?></td><td><?php echo h($type['description']); ?></td><td><?php echo !empty($type['is_active'])?'활성':'비활성'; ?></td><td><form method="post" class="gov-form"><input type="hidden" name="_csrf" value="<?php echo h(csrf_token()); ?>"><input type="hidden" name="action" value="save_type"><input type="hidden" name="id" value="<?php echo (int)$type['id']; ?>"><input name="type_code" value="<?php echo h($type['type_code']); ?>" required><input name="type_name" value="<?php echo h($type['type_name']); ?>" required><input name="description" value="<?php echo h($type['description']); ?>"><label><input type="checkbox" name="is_active" value="1" <?php echo !empty($type['is_active'])?'checked':''; ?>> 활성</label><input type="number" name="sort_order" value="<?php echo (int)$type['sort_order']; ?>" style="width:75px"><input name="reason" required placeholder="변경사유"><button>저장</button></form></td></tr><?php endforeach;endif; ?></tbody></table></div>
  <form method="post" class="gov-form" style="margin-top:14px"><input type="hidden" name="_csrf" value="<?php echo h(csrf_token()); ?>"><input type="hidden" name="action" value="assign_project"><label>현장<select name="project_id" required><option value="">선택</option><?php foreach($govProjects as $project): ?><option value="<?php echo (int)$project['id']; ?>"><?php echo h(trim((string)$project['name'])!==''?$project['name']:'현장정보 확인 필요'); ?></option><?php endforeach; ?></select></label><label>현장유형<select name="project_type_id"><option value="0">미지정</option><?php foreach($govTypes as $type):if(empty($type['is_active']))continue; ?><option value="<?php echo (int)$type['id']; ?>"><?php echo h($type['type_name']); ?></option><?php endforeach; ?></select></label><label>지정사유<input name="reason" required maxlength="500"></label><button>현장유형 지정</button></form>
 </section>
 <section class="gov-card"><h3>데이터 원천 분류현황</h3><form method="get" class="gov-form"><input type="hidden" name="r" value="admin/ai_data_governance"><label>원천<select name="origin"><option value="">전체</option><?php foreach($govOriginLabels as $code=>$label): ?><option value="<?php echo h($code); ?>" <?php echo isset($_GET['origin'])&&$_GET['origin']===$code?'selected':''; ?>><?php echo h($label); ?> (<?php echo h($code); ?>)</option><?php endforeach; ?></select></label><button>조회</button></form>
 <div class="gov-scroll"><table class="gov-table" style="margin-top:12px"><thead><tr><th>현장</th><th>비용항목</th><th>발생일</th><th>귀속월</th><th>최초 입력일</th><th>원천</th><th>학습사용</th><th>검토</th></tr></thead><tbody><?php if(count($govRows)===0): ?><tr><td colspan="8">표시할 분류자료가 없습니다.</td></tr><?php else:foreach($govRows as $row): ?><tr><td><?php echo h(trim((string)$row['project_name'])!==''?$row['project_name']:'현장정보 확인 필요'); ?></td><td><?php echo h($row['cost_type']); ?></td><td><?php echo h($row['occurred_date']!==null?$row['occurred_date']:'알 수 없음'); ?></td><td><?php echo h($row['accounting_month']!==null?$row['accounting_month']:'확인 필요'); ?></td><td><?php echo h($row['entered_at']!==null?$row['entered_at']:'알 수 없음'); ?></td><td><?php echo h(AiCostDataGovernanceService::originLabel($row['data_origin'])); ?><br><small><?php echo h($row['data_origin']); ?></small></td><td>금액 <?php echo !empty($row['is_amount_eligible'])?'사용':'제외'; ?><br>시점 <?php echo !empty($row['is_timing_eligible'])?'사용':'제외'; ?></td><td><form method="post" class="gov-form"><input type="hidden" name="_csrf" value="<?php echo h(csrf_token()); ?>"><input type="hidden" name="action" value="review_origin"><input type="hidden" name="map_id" value="<?php echo (int)$row['id']; ?>"><select name="data_origin"><?php foreach($govOriginLabels as $code=>$label): ?><option value="<?php echo h($code); ?>" <?php echo $row['data_origin']===$code?'selected':''; ?>><?php echo h($label); ?></option><?php endforeach; ?></select><label><input type="checkbox" name="amount_eligible" value="1" <?php echo !empty($row['is_amount_eligible'])?'checked':''; ?>>금액</label><label><input type="checkbox" name="timing_eligible" value="1" <?php echo !empty($row['is_timing_eligible'])?'checked':''; ?>>시점</label><input name="reason" required maxlength="500" placeholder="검토사유"><button>저장</button></form></td></tr><?php endforeach;endif; ?></tbody></table></div></section>
</div>
