<?php
/** Forecast versus separately versioned actual-close results. PHP 5.6 compatible. */
use App\Core\Auth;
use App\Core\Db;
use App\Services\AiForecastAccuracyService;
use App\Services\AiCostForecastV2Service;
require_once __DIR__ . '/../../services/AiForecastAccuracyService.php';
if(!Auth::check()||!Auth::isDevelopmentDepartment()){http_response_code(403);echo h('접근 권한이 없습니다.');return;}
$accPdo=null;$accResult=null;try{$accPdo=Db::pdo();}catch(Exception $e){$accResult=array('ok'=>false,'message'=>'DB 연결 상태를 확인할 수 없습니다.');}
if($_SERVER['REQUEST_METHOD']==='POST'){$token=isset($_POST['_csrf'])?(string)$_POST['_csrf']:'';$action=isset($_POST['action'])?(string)$_POST['action']:'';if(!csrf_check($token))$accResult=array('ok'=>false,'message'=>'보안 토큰이 올바르지 않습니다.');else if(!$accPdo)$accResult=array('ok'=>false,'message'=>'DB 연결 상태를 확인할 수 없습니다.');else if($action==='install')$accResult=AiForecastAccuracyService::installOrUpdate($accPdo);else if($action==='capture')$accResult=AiForecastAccuracyService::captureClosedActuals($accPdo,date('Y-m-d'),'개발부서 웹 화면 정상 마감 집계');else if($action==='evaluate')$accResult=AiForecastAccuracyService::evaluate($accPdo);else $accResult=array('ok'=>false,'message'=>'요청값이 올바르지 않습니다.');}
$accStatus=$accPdo?AiForecastAccuracyService::schemaStatus($accPdo):array('installed'=>false);$accFilters=array('target_ym'=>isset($_GET['target_ym'])?$_GET['target_ym']:'');$accSummary=$accPdo?AiForecastAccuracyService::summary($accPdo,$accFilters):array('count'=>0,'mean_absolute_error'=>null,'wape'=>null,'range_hit_rate'=>null,'over_rate'=>null,'under_rate'=>null);$accBreakdowns=$accPdo?AiForecastAccuracyService::performanceBreakdowns($accPdo,$accFilters):array('projects'=>array(),'cost_types'=>array(),'close_windows'=>array());$accRows=$accPdo?AiForecastAccuracyService::listAccuracy($accPdo,$accFilters,1,100):array();$accLabels=AiCostForecastV2Service::categoryLabels();
if(!function_exists('cpms_acc_money')){function cpms_acc_money($v){return $v===null?'-':number_format((float)$v,0).'원';}}
if(!function_exists('cpms_acc_rate')){function cpms_acc_rate($v){return $v===null?'-':number_format((float)$v*100,1).'%';}}
if(!function_exists('cpms_acc_direction')){function cpms_acc_direction($v){return $v==='OVER'?'과대예측':($v==='UNDER'?'과소예측':'일치');}}
?>
<style>.acc{color:#0f172a}.acc *{box-sizing:border-box}.acc-card{background:#fff;border:1px solid #e2e8f0;border-radius:18px;padding:20px;margin:14px 0}.acc-grid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:10px}.acc-stat{background:#f8fafc;border-radius:12px;padding:14px}.acc-stat small{display:block;color:#64748b}.acc-stat strong{font-size:18px}.acc-actions{display:flex;gap:8px;flex-wrap:wrap}.acc button,.acc a{border:0;border-radius:9px;padding:10px 13px;background:#1d4ed8;color:#fff;font-weight:900;text-decoration:none}.acc input{border:1px solid #cbd5e1;border-radius:9px;padding:9px}.acc-msg{padding:12px;border-radius:10px;background:#ecfdf5;color:#047857}.acc-msg.bad{background:#fef2f2;color:#b91c1c}.acc-scroll{overflow:auto}.acc table{border-collapse:collapse;width:100%;min-width:1450px}.acc .acc-compact{min-width:760px}.acc th,.acc td{border:1px solid #e2e8f0;padding:9px;text-align:left}.acc-note{color:#64748b;font-size:13px}@media(max-width:1100px){.acc-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:800px){.acc-grid{grid-template-columns:1fr 1fr}.acc-actions form,.acc-actions button{width:100%}}</style>
<div class="acc"><section class="acc-card"><h2>예측 정확도</h2><p class="acc-note">각 실행 당시의 예측값은 그대로 두고, 마감 이후 확정한 실제금액 버전과 별도로 연결합니다. 실제금액이 0원이면 비율오차는 계산하지 않습니다.</p><?php if(is_array($accResult)): ?><div class="acc-msg <?php echo empty($accResult['ok'])?'bad':''; ?>"><?php echo h(isset($accResult['message'])?$accResult['message']:'처리 결과를 확인해주세요.'); ?></div><?php endif; ?><div class="acc-actions" style="margin-top:12px"><form method="post"><input type="hidden" name="_csrf" value="<?php echo h(csrf_token()); ?>"><input type="hidden" name="action" value="install"><button>설치/확인</button></form><form method="post"><input type="hidden" name="_csrf" value="<?php echo h(csrf_token()); ?>"><input type="hidden" name="action" value="capture"><button>마감 실제금액 버전 확정</button></form><form method="post"><input type="hidden" name="_csrf" value="<?php echo h(csrf_token()); ?>"><input type="hidden" name="action" value="evaluate"><button>정확도 계산</button></form><a href="?r=admin%2Fai_data_governance">데이터 원천 관리</a></div></section>
<section class="acc-grid"><div class="acc-stat"><small>구조 상태</small><strong><?php echo !empty($accStatus['installed'])?'설치 완료':'미설치'; ?></strong></div><div class="acc-stat"><small>비교 예측 수</small><strong><?php echo number_format((int)$accSummary['count']); ?>건</strong></div><div class="acc-stat"><small>평균 절대오차</small><strong><?php echo h(cpms_acc_money($accSummary['mean_absolute_error'])); ?></strong></div><div class="acc-stat"><small>회사 금액가중 오차율</small><strong><?php echo h(cpms_acc_rate($accSummary['wape'])); ?></strong></div><div class="acc-stat"><small>예상범위 적중률</small><strong><?php echo $accSummary['range_hit_rate']===null?'-':h(number_format((float)$accSummary['range_hit_rate'],1).'%'); ?></strong></div><div class="acc-stat"><small>과대예측 비율</small><strong><?php echo $accSummary['over_rate']===null?'-':h(number_format((float)$accSummary['over_rate'],1).'%'); ?></strong></div><div class="acc-stat"><small>과소예측 비율</small><strong><?php echo $accSummary['under_rate']===null?'-':h(number_format((float)$accSummary['under_rate'],1).'%'); ?></strong></div></section>
<?php $accBreakdownSections=array('projects'=>'현장별 성능','cost_types'=>'비용항목별 성능','close_windows'=>'마감 잔여일 구간별 성능');foreach($accBreakdownSections as $breakdownKey=>$breakdownTitle):$breakdownRows=isset($accBreakdowns[$breakdownKey])&&is_array($accBreakdowns[$breakdownKey])?$accBreakdowns[$breakdownKey]:array(); ?><section class="acc-card"><h3><?php echo h($breakdownTitle); ?></h3><div class="acc-scroll"><table class="acc-compact"><thead><tr><th>구분</th><th>표본</th><th>평균 절대오차</th><th>금액가중 오차율</th><th>범위 적중률</th><th>과대</th><th>과소</th></tr></thead><tbody><?php if(count($breakdownRows)===0): ?><tr><td colspan="7">계산 가능한 성능자료가 없습니다.</td></tr><?php else:foreach($breakdownRows as $breakdownRow):$groupLabel=isset($breakdownRow['group_label'])?$breakdownRow['group_label']:'확인 필요';if($breakdownKey==='cost_types'&&isset($accLabels[$breakdownRow['group_key']]))$groupLabel=$accLabels[$breakdownRow['group_key']]; ?><tr><td><?php echo h($groupLabel); ?></td><td><?php echo number_format((int)$breakdownRow['sample_count']); ?>건</td><td><?php echo h(cpms_acc_money($breakdownRow['mean_absolute_error'])); ?></td><td><?php echo h(cpms_acc_rate($breakdownRow['wape'])); ?></td><td><?php echo $breakdownRow['range_hit_rate']===null?'-':h(number_format((float)$breakdownRow['range_hit_rate'],1).'%'); ?></td><td><?php echo $breakdownRow['over_rate']===null?'-':h(number_format((float)$breakdownRow['over_rate'],1).'%'); ?></td><td><?php echo $breakdownRow['under_rate']===null?'-':h(number_format((float)$breakdownRow['under_rate'],1).'%'); ?></td></tr><?php endforeach;endif; ?></tbody></table></div></section><?php endforeach; ?>
<section class="acc-card"><form method="get" class="acc-actions"><input type="hidden" name="r" value="admin/ai_forecast_accuracy"><input type="month" name="target_ym" value="<?php echo h($accFilters['target_ym']); ?>"><button>조회</button></form><div class="acc-scroll" style="margin-top:12px"><table><thead><tr><th>대상월</th><th>분석일</th><th>현장명</th><th>비용항목</th><th>당시 현재 입력액</th><th>미입력 예상액</th><th>최종 예상액</th><th>예상범위</th><th>실제 마감액</th><th>절대오차</th><th>방향</th><th>범위 적중</th><th>금액패턴</th><th>입력시점패턴</th><th>예측방식</th><th>원천 구성</th></tr></thead><tbody><?php if(count($accRows)===0): ?><tr><td colspan="16">마감 실제금액과 연결된 예측 정확도 자료가 없습니다.</td></tr><?php else:foreach($accRows as $row): ?><tr><td><?php echo h($row['target_ym']); ?></td><td><?php echo h($row['analysis_date']); ?></td><td><?php echo h(trim((string)$row['project_name'])!==''?$row['project_name']:'현장정보 확인 필요'); ?></td><td><?php echo h(isset($accLabels[$row['cost_type']])?$accLabels[$row['cost_type']]:'비용항목 확인 필요'); ?></td><td><?php echo h(cpms_acc_money($row['current_entered_amount'])); ?></td><td><?php echo h(cpms_acc_money($row['expected_unentered_amount'])); ?></td><td><?php echo h(cpms_acc_money($row['final_expected_amount'])); ?></td><td><?php echo h(cpms_acc_money($row['expected_lower_amount']).' ~ '.cpms_acc_money($row['expected_upper_amount'])); ?></td><td><?php echo h(cpms_acc_money($row['actual_amount'])); ?></td><td><?php echo h(cpms_acc_money($row['absolute_error'])); ?><?php echo $row['absolute_percentage_error']===null?' / 비율 산정 안 함':' / '.h(cpms_acc_rate($row['absolute_percentage_error'])); ?></td><td><?php echo h(cpms_acc_direction($row['error_direction'])); ?></td><td><?php echo !empty($row['in_expected_range'])?'적중':'범위 밖'; ?></td><td><?php echo (int)$row['amount_pattern_month_count']; ?>개월</td><td><?php echo (int)$row['timing_pattern_month_count']; ?>개월</td><td><?php echo h($row['prediction_method']); ?></td><td><small><?php echo h($row['data_origin_summary']); ?></small></td></tr><?php endforeach;endif; ?></tbody></table></div></section></div>
