<?php /** 출퇴근 시스템 DB 설정 버튼 실행 페이지 */ require_once __DIR__.'/../app/bootstrap.php'; if(!\App\Core\Auth::canManageEmployees()){die('권한없음');} $pdo=\App\Core\Db::pdo(); if(!$pdo){die('DB 연결 실패');}
$action=isset($_POST['action'])?$_POST['action']:''; $msg='';
function run_att_sql($pdo,$keys){$defs=array(
'records'=>"CREATE TABLE IF NOT EXISTS cpms_attendance_records (id INT AUTO_INCREMENT PRIMARY KEY, employee_id INT NOT NULL, work_date DATE NOT NULL, check_in DATETIME NULL, check_out DATETIME NULL, status VARCHAR(30) NOT NULL DEFAULT '출근전', raw_minutes INT NOT NULL DEFAULT 0, work_minutes INT NOT NULL DEFAULT 0, memo VARCHAR(255) DEFAULT '', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY uq_emp_date(employee_id,work_date), INDEX idx_work_date(work_date), INDEX idx_employee_id(employee_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
'requests'=>"CREATE TABLE IF NOT EXISTS cpms_attendance_requests (id INT AUTO_INCREMENT PRIMARY KEY, employee_id INT NOT NULL, request_date DATE NOT NULL, request_type VARCHAR(30) NOT NULL, requested_check_in DATETIME NULL, requested_check_out DATETIME NULL, reason TEXT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending', reviewed_by INT NULL, reviewed_at DATETIME NULL, reject_reason TEXT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX idx_employee_id(employee_id), INDEX idx_request_date(request_date), INDEX idx_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
'leave_records'=>"CREATE TABLE IF NOT EXISTS cpms_leave_records (id INT AUTO_INCREMENT PRIMARY KEY, employee_id INT NOT NULL, leave_date DATE NOT NULL, leave_type VARCHAR(30) NOT NULL, leave_amount DECIMAL(4,2) NOT NULL DEFAULT 1.0, reason VARCHAR(255) DEFAULT '', created_by INT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX idx_employee_id(employee_id), INDEX idx_leave_date(leave_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
'leave_adjustments'=>"CREATE TABLE IF NOT EXISTS cpms_leave_adjustments (id INT AUTO_INCREMENT PRIMARY KEY, employee_id INT NOT NULL, leave_type VARCHAR(30) NOT NULL, amount DECIMAL(6,2) NOT NULL, reason VARCHAR(255) DEFAULT '', created_by INT NULL, created_at DATETIME NOT NULL, INDEX idx_employee_id(employee_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
'settings'=>"CREATE TABLE IF NOT EXISTS cpms_attendance_settings (setting_key VARCHAR(80) PRIMARY KEY, setting_value VARCHAR(255) NOT NULL, updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
foreach($keys as $k){$pdo->exec($defs[$k]);}
$pdo->exec("ALTER TABLE cpms_attendance_records ADD COLUMN raw_minutes INT NOT NULL DEFAULT 0");
}
try{if($action==='records')run_att_sql($pdo,array('records')); if($action==='requests')run_att_sql($pdo,array('requests')); if($action==='leave')run_att_sql($pdo,array('leave_records','leave_adjustments')); if($action==='settings')run_att_sql($pdo,array('settings')); if($action==='all')run_att_sql($pdo,array('records','requests','leave_records','leave_adjustments','settings')); $now=date('Y-m-d H:i:s'); if($action!==''){foreach(array('standard_weekly_hours'=>'40','max_weekly_hours'=>'52','daily_break_deduct_minutes'=>'120','under_one_year_monthly_leave'=>'1','half_day_amount'=>'0.5','leave_rule_after_one_year'=>'half_year','week_start'=>'monday') as $k=>$v){$st=$pdo->prepare("REPLACE INTO cpms_attendance_settings(setting_key,setting_value,updated_at) VALUES(:k,:v,:u)");$st->execute(array(':k'=>$k,':v'=>$v,':u'=>$now));} $msg='처리 완료: '.$action;}}catch(Exception $e){$msg='오류: '.$e->getMessage();}
?>
<h3>출퇴근 DB 설정</h3>
<p><?php echo h($msg);?></p>
<form method='post'><!-- 출퇴근 DB 설정 버튼 --><button name='action' value='records'>1) 출퇴근 기록 테이블 생성/확인</button></form>
<form method='post'><button name='action' value='requests'>2) 출퇴근 요청 테이블 생성/확인</button></form>
<form method='post'><button name='action' value='leave'>3) 연차/월차/반차 테이블 생성/확인</button></form>
<form method='post'><button name='action' value='settings'>4) 근태 설정 테이블 생성/확인</button></form>
<form method='post'><button name='action' value='all'>5) 전체 근태 테이블 생성/확인</button></form>
<p><a href='?r=management/attendance'>관리 화면으로</a></p>