<section class="ceo-v2-card"><div class="ceo-v2-grid">
 <div class="ceo-v2-kpi"><small>CEO Index</small><strong><?php echo h(cpms_ceo_v2_score(isset($ceoIndexV2['ceo_index_score'])?$ceoIndexV2['ceo_index_score']:null)); ?></strong><span class="ceo-v2-badge"><?php echo h(isset($ceoIndexV2['ceo_index_grade'])?\App\Services\AiCeoIndexService::gradeLabel($ceoIndexV2['ceo_index_grade']):'분석 전'); ?></span></div>
 <div class="ceo-v2-kpi"><small>현재 입력 투입비</small><strong><?php echo h(cpms_ceo_v2_money(isset($ceoSummary['current_input_total'])?$ceoSummary['current_input_total']:null)); ?></strong></div>
 <div class="ceo-v2-kpi"><small>최종 예상 투입비</small><strong><?php echo h(cpms_ceo_v2_money(isset($ceoSummary['final_forecast_total'])?$ceoSummary['final_forecast_total']:null)); ?></strong><small><?php echo h(cpms_ceo_v2_money(isset($ceoSummary['forecast_low_total'])?$ceoSummary['forecast_low_total']:null)); ?> ~ <?php echo h(cpms_ceo_v2_money(isset($ceoSummary['forecast_high_total'])?$ceoSummary['forecast_high_total']:null)); ?></small></div>
 <div class="ceo-v2-kpi"><small>예측 신뢰도</small><strong style="font-size:16px"><?php echo h(cpms_ai_display_confidence(isset($ceoSummary['confidence_score'])?$ceoSummary['confidence_score']:null,isset($ceoSummary['confidence_grade'])?$ceoSummary['confidence_grade']:'')); ?></strong><small><?php echo h(isset($ceoLearning['state']['label'])?$ceoLearning['state']['label']:'학습자료 없음'); ?></small></div>
 <div class="ceo-v2-kpi"><small>예상 입력완료율</small><strong><?php echo h(cpms_ceo_v2_rate(isset($ceoSummary['expected_completion_rate'])?$ceoSummary['expected_completion_rate']:null)); ?></strong></div>
 <div class="ceo-v2-kpi"><small>미입력 예상금액</small><strong><?php echo h(cpms_ceo_v2_money(isset($ceoSummary['expected_unentered_total'])?$ceoSummary['expected_unentered_total']:null)); ?></strong></div>
 <div class="ceo-v2-kpi"><small>긴급 확인 현장</small><strong><?php echo isset($ceoIndexV2['critical_count'])?h((int)$ceoIndexV2['critical_count'].'개'):'-'; ?></strong></div>
 <div class="ceo-v2-kpi"><small>대상 월 · 최근 분석</small><strong><?php echo h($ceoTargetYm); ?></strong><small><?php echo h(isset($ceoSummary['last_calculated_at'])&&$ceoSummary['last_calculated_at']!==''?$ceoSummary['last_calculated_at']:'최신 분석 없음'); ?></small></div>
</div></section>
