<?php
$ceoForecastContext=$ceoSectionPdo?\App\Services\AiCostForecastV2Service::latestContext($ceoSectionPdo,$ceoTargetYm):array('available'=>false);
$ceoForecastPage=isset($_GET['page'])?max(1,(int)$_GET['page']):1;
$ceoIncludeZero=!empty($_GET['include_zero']);$ceoForecastFilters=array('include_zero'=>$ceoIncludeZero);
$ceoForecastTotal=$ceoSectionPdo?\App\Services\AiCostForecastV2Service::countResults($ceoSectionPdo,$ceoForecastContext,$ceoForecastFilters):0;
$ceoForecastPages=max(1,(int)ceil($ceoForecastTotal/50));if($ceoForecastPage>$ceoForecastPages)$ceoForecastPage=$ceoForecastPages;
$ceoForecastRows=$ceoSectionPdo?\App\Services\AiCostForecastV2Service::listResults($ceoSectionPdo,$ceoForecastContext,$ceoForecastFilters,$ceoForecastPage,50):array();
$ceoDetailProject=isset($_GET['project_id'])?(int)$_GET['project_id']:0;
$ceoCategoryRows=$ceoDetailProject>0&&$ceoSectionPdo&&!empty($ceoForecastContext['available'])?\App\Services\AiCostForecastV2Service::categoryRows($ceoSectionPdo,$ceoForecastContext['analysis_date'],$ceoForecastContext['target_ym'],$ceoDetailProject,$ceoForecastContext['run_id']):array();
$ceoCategoryLabels=\App\Services\AiCostForecastV2Service::categoryLabels();
?>
<section class="ceo-v2-card"><h3>투입비 예측</h3><p>현재 입력금액과 과거 입력시점을 참고하여 아직 입력되지 않았을 가능성이 있는 금액을 함께 예상합니다.</p>
 <form method="get" class="ceo-v2-filter"><input type="hidden" name="r" value="ceo_index"><input type="hidden" name="tab" value="forecast"><input type="hidden" name="target_ym" value="<?php echo h($ceoTargetYm); ?>"><label><input type="checkbox" name="include_zero" value="1"<?php echo $ceoIncludeZero?' checked':''; ?> onchange="this.form.submit()"> 0원 현장 포함</label></form>
 <div class="ceo-v2-scroll"><table class="ceo-v2-table"><thead><tr><th>현장</th><th>현재 입력</th><th>입력완료율</th><th>미입력 예상</th><th>최종 예상</th><th>예상범위</th><th>분석 신뢰도</th><th>예측 방식</th><th>상세보기</th></tr></thead><tbody>
 <?php if(count($ceoForecastRows)===0): ?><tr><td colspan="9">표시할 투입비 예측결과가 없습니다.</td></tr><?php else:foreach($ceoForecastRows as $row): ?><tr>
  <td><?php echo h(trim((string)$row['project_name_snapshot'])!==''?$row['project_name_snapshot']:'현장정보 확인 필요'); ?></td><td><?php echo h(cpms_ceo_v2_money($row['current_input_amount'])); ?></td><td><?php echo h(cpms_ceo_v2_rate($row['expected_completion_rate'])); ?></td><td><?php echo h(cpms_ceo_v2_money($row['expected_unentered_amount'])); ?></td><td><strong><?php echo h(cpms_ceo_v2_money($row['final_forecast_amount'])); ?></strong></td><td><?php echo h(cpms_ceo_v2_money($row['forecast_low_amount'])); ?> ~ <?php echo h(cpms_ceo_v2_money($row['forecast_high_amount'])); ?></td><td><?php echo h(cpms_ceo_confidence_text($row['forecast_confidence_score'],$row['forecast_confidence_grade'])); ?></td><td><?php echo h(cpms_ceo_label_text($row['forecast_method'],false)); ?></td><td><a href="<?php echo h(cpms_ceo_v2_url('forecast',$ceoTargetYm,array('project_id'=>(int)$row['project_id'],'include_zero'=>$ceoIncludeZero?1:0))); ?>">항목별 보기</a></td>
 </tr><?php endforeach;endif; ?></tbody></table></div>
 <?php if($ceoForecastPages>1): ?><div class="ceo-v2-actions" style="margin-top:10px"><?php if($ceoForecastPage>1): ?><a class="ceo-v2-btn secondary" href="<?php echo h(cpms_ceo_v2_url('forecast',$ceoTargetYm,array('page'=>$ceoForecastPage-1,'include_zero'=>$ceoIncludeZero?1:0))); ?>">이전</a><?php endif; ?><span><?php echo h($ceoForecastPage.' / '.$ceoForecastPages); ?></span><?php if($ceoForecastPage<$ceoForecastPages): ?><a class="ceo-v2-btn secondary" href="<?php echo h(cpms_ceo_v2_url('forecast',$ceoTargetYm,array('page'=>$ceoForecastPage+1,'include_zero'=>$ceoIncludeZero?1:0))); ?>">다음</a><?php endif; ?></div><?php endif; ?>
</section>
<section class="ceo-v2-card"><h3>학습 상태</h3><div class="ceo-v2-grid"><div class="ceo-v2-kpi"><small>학습 상태</small><strong><?php echo h(isset($ceoLearning['state']['label'])?$ceoLearning['state']['label']:'학습자료 없음'); ?></strong></div><div class="ceo-v2-kpi"><small>학습에 사용한 기간</small><strong><?php echo h(cpms_ceo_learning_period($ceoLearning)); ?></strong></div><div class="ceo-v2-kpi"><small>마감자료</small><strong><?php echo h(!empty($ceoLearning['month_count'])?'최종 마감자료 '.(int)$ceoLearning['month_count'].'개월':'최종 마감자료 없음'); ?></strong></div><div class="ceo-v2-kpi"><small>예측 기준</small><strong><?php echo h((int)$ceoLearning['month_count']===1?'기본예측 + 최근 마감월 입력패턴 참고':((int)$ceoLearning['month_count']>=3?'입력패턴 정상 반영':'기본 예측 적용')); ?></strong></div></div><?php if((int)$ceoLearning['month_count']===1): ?><div class="ceo-v2-note">현재 최종 마감자료 한 달을 참고하고 있습니다. 자료가 누적되면 현장별 예측 신뢰도가 개선됩니다.</div><?php elseif(empty($ceoLearning['month_count'])): ?><div class="ceo-v2-note">과거 입력자료가 충분하지 않아 현재는 정확한 신뢰도를 산정하기 어렵습니다.</div><?php endif; ?></section>
<?php if($ceoDetailProject>0): ?><section class="ceo-v2-card"><h3>비용항목별 예측</h3><div class="ceo-v2-scroll"><table class="ceo-v2-table"><thead><tr><th>비용항목</th><th>현재</th><th>입력완료율</th><th>미입력 예상</th><th>최종 예상</th><th>범위</th><th>분석 신뢰도</th><th>평균 입력지연</th><th>가능성</th><th>적용 기준</th></tr></thead><tbody><?php foreach($ceoCategoryRows as $row): ?><tr><td><?php echo h(isset($ceoCategoryLabels[$row['cost_type']])?$ceoCategoryLabels[$row['cost_type']]:$row['cost_type']); ?></td><td><?php echo h(cpms_ceo_v2_money($row['current_input_amount'])); ?></td><td><?php echo h(cpms_ceo_v2_rate($row['expected_completion_rate'])); ?></td><td><?php echo h(cpms_ceo_v2_money($row['expected_unentered_amount'])); ?></td><td><?php echo h(cpms_ceo_v2_money($row['final_forecast_amount'])); ?></td><td><?php echo h(cpms_ceo_v2_money($row['forecast_low_amount'])); ?> ~ <?php echo h(cpms_ceo_v2_money($row['forecast_high_amount'])); ?></td><td><?php echo h(cpms_ceo_confidence_text($row['forecast_confidence_score'],$row['forecast_confidence_grade'])); ?></td><td><?php echo h($row['average_input_lag_days']===null?'-':number_format((float)$row['average_input_lag_days'],1).'일'); ?></td><td>과다 <?php echo h(cpms_ceo_label_text($row['overinput_grade'],false)); ?> · 미입력 <?php echo h(cpms_ceo_label_text($row['missing_possibility_grade'],false)); ?></td><td><?php echo h(cpms_ceo_label_text($row['fallback_level'],false)); ?></td></tr><?php endforeach; ?></tbody></table></div><div class="ceo-v2-note">현장 자료가 부족한 항목은 회사 전체 비용항목 자료와 기본예측을 참고합니다.</div></section><?php endif; ?>
