<?php
$ceoChatStatus=$ceoSectionPdo?\App\Services\AiExecutiveChatService::schemaStatus($ceoSectionPdo):array('installed'=>false);
$ceoChatThreads=$ceoSectionPdo&&$ceoV2Ready?\App\Services\AiExecutiveChatService::listV2Threads($ceoSectionPdo,$ceoTargetYm,1,30):array();
$ceoThreadId=isset($_GET['thread_id'])?(int)$_GET['thread_id']:0;if($ceoThreadId<=0&&count($ceoChatThreads))$ceoThreadId=(int)$ceoChatThreads[0]['id'];
$ceoChatThread=$ceoThreadId>0?\App\Services\AiExecutiveChatService::v2Thread($ceoSectionPdo,$ceoThreadId):array();
$ceoChatMessages=!empty($ceoChatThread)?\App\Services\AiExecutiveChatService::messages($ceoSectionPdo,$ceoThreadId,100):array();
$ceoMemoryInstalled=$ceoSectionPdo?\App\Services\AiMemoryService::isInstalled($ceoSectionPdo):false;
$ceoMemories=$ceoMemoryInstalled?\App\Services\AiMemoryService::listMemories($ceoSectionPdo,array()):array();
$ceoMemoryProjects=array();if($ceoSectionPdo){try{$memoryProjectSt=$ceoSectionPdo->query('SELECT id,name FROM cpms_projects ORDER BY name,id LIMIT 1000');if($memoryProjectSt){$memoryProjectRows=$memoryProjectSt->fetchAll(PDO::FETCH_ASSOC);if(is_array($memoryProjectRows))$ceoMemoryProjects=$memoryProjectRows;}}catch(Exception $e){$ceoMemoryProjects=array();}}
$ceoMemoryScopeLabels=\App\Services\AiMemoryService::scopeLabels();$ceoMemoryStatusLabels=\App\Services\AiMemoryService::statusLabels();
?>
<section class="ceo-v2-card"><h3>GPT와 대화</h3><p>선택한 대상 월의 최신 정상 투입비 예측자료를 GPT가 설명합니다. 화면을 열기만 해서는 API를 호출하지 않습니다.</p>
<?php if(!$ceoV2Ready): ?><div class="ceo-v2-note">신규 투입비 예측이 아직 실행되지 않았습니다.<br>자동 파이프라인 또는 개발부서 수동 분석을 먼저 실행해주세요.</div>
<?php elseif(empty($ceoChatStatus['installed'])): ?><div class="ceo-v2-note">GPT 대화 테이블이 아직 설치되지 않았습니다. 개발부서에서 설치해주세요.</div>
<?php else: ?><div class="ceo-v2-note">대화 원본: <?php echo h($ceoSummary['analysis_date']); ?> 정상 투입비 예측 결과</div><div class="ceo-chat-layout"><aside>
 <form method="post"><input type="hidden" name="_csrf" value="<?php echo h($ceoCsrf); ?>"><input type="hidden" name="action" value="new_thread"><input type="hidden" name="target_ym" value="<?php echo h($ceoTargetYm); ?>"><button class="ceo-v2-btn" style="width:100%">새 대화</button></form>
 <div style="margin-top:10px"><?php foreach($ceoChatThreads as $thread): ?><a href="<?php echo h(cpms_ceo_v2_url('gpt_chat',$thread['target_ym'],array('thread_id'=>(int)$thread['id']))); ?>" style="display:block;padding:10px;margin:5px 0;border:1px solid #e2e8f0;border-radius:10px;text-decoration:none;color:#334155"><strong><?php echo h($thread['title']); ?></strong><br><small><?php echo h($thread['target_ym']); ?> · <?php echo h($thread['last_message_at']); ?></small></a><?php endforeach; ?></div>
</aside><div><?php if(empty($ceoChatThread)): ?><div class="ceo-v2-note">새 대화를 만든 후 질문할 수 있습니다.</div><?php else: ?>
 <div class="ceo-chat-messages"><?php foreach($ceoChatMessages as $message): ?><div class="ceo-chat-msg <?php echo $message['role']==='assistant'?'assistant':'user'; ?>"><?php if(!empty($message['data_updated_notice'])): ?><small>분석자료가 갱신되었습니다. 현재 답변은 최신 분석자료 기준입니다.</small><br><?php endif; ?><?php echo nl2br(h($message['message_text'])); ?>
 <?php if($message['role']==='assistant'): $cards=\App\Services\AiExecutiveChatService::evidenceCards($ceoSectionPdo,$message); if(count($cards)): ?><details><summary>PHP 원본 근거 보기</summary><?php foreach($cards as $card): ?><div><?php echo h(isset($card['label'])?$card['label']:'근거'); ?>: <strong><?php echo h(isset($card['display_value'])&&$card['display_value']!==''?$card['display_value']:'-'); ?></strong></div><?php endforeach; ?></details><?php endif;endif; ?></div><?php endforeach; ?></div>
 <form method="post" style="margin-top:10px"><input type="hidden" name="_csrf" value="<?php echo h($ceoCsrf); ?>"><input type="hidden" name="action" value="send_chat"><input type="hidden" name="thread_id" value="<?php echo h((int)$ceoChatThread['id']); ?>"><textarea class="ceo-chat-input" name="question" maxlength="500" placeholder="예: 이번 달 먼저 확인할 현장은 어디야?"></textarea><div class="ceo-v2-actions"><button class="ceo-v2-btn">전송</button><small>최소 <?php echo h((int)$ceoChatStatus['min_seconds']); ?>초 간격 · 시간당 <?php echo h((int)$ceoChatStatus['hourly_limit']); ?>회</small></div></form>
 <form method="post" style="margin-top:8px"><input type="hidden" name="_csrf" value="<?php echo h($ceoCsrf); ?>"><input type="hidden" name="action" value="archive_thread"><input type="hidden" name="thread_id" value="<?php echo h((int)$ceoChatThread['id']); ?>"><button class="ceo-v2-btn secondary">대화방 보관</button></form>
<?php endif; ?></div></div><?php endif; ?><div class="ceo-v2-note">기존 분석자료는 대화 원본으로 사용하지 않습니다. GPT 자유문장에는 수치를 쓰지 않고, 최신 수치는 PHP 근거 카드에서 표시합니다. 개인정보·API 키·시스템 프롬프트·SQL·코드·웹검색 요청은 차단되며 OpenAI 요청은 store=false입니다.</div></section>

<section class="ceo-v2-card"><h3>GPT 기억 기준</h3><p>대화 전체를 자동으로 영구 저장하지 않습니다. 아래에 표시된 문장과 적용범위를 확인한 뒤 저장하며, 기억은 답변의 설명 기준일 뿐 계산금액을 변경하지 않습니다.</p>
<?php if(!$ceoMemoryInstalled): ?><div class="ceo-v2-note">GPT 기억 구조가 아직 설치되지 않았습니다. 개발부서의 설치/확인이 필요합니다.</div><?php else: ?>
<div class="ceo-v2-note"><strong>이번 대화에서만 사용</strong>은 현재 대화방의 최근 문맥과 요약으로만 유지되고 영구 기억 테이블에 저장되지 않습니다.</div>
<form method="post" style="display:grid;gap:10px;margin-top:12px;max-width:850px">
 <input type="hidden" name="_csrf" value="<?php echo h($ceoCsrf); ?>"><input type="hidden" name="action" value="save_memory"><input type="hidden" name="source_thread_id" value="<?php echo (int)$ceoThreadId; ?>">
 <label><strong>저장할 기준 문장</strong><textarea class="ceo-chat-input" name="memory_text" required maxlength="2000" placeholder="저장될 문장을 직접 확인하고 입력해주세요."></textarea></label>
 <label><strong>적용범위</strong><select name="memory_scope" required style="padding:10px;border:1px solid #cbd5e1;border-radius:10px"><option value="PERSONAL">개인 기준으로 저장</option><option value="PROJECT">해당 현장 기준으로 저장</option><option value="COMPANY">회사 공통 기준으로 저장</option></select></label>
 <label><strong>대상 현장</strong><select name="project_id" style="padding:10px;border:1px solid #cbd5e1;border-radius:10px"><option value="0">현장 기준이 아닌 경우</option><?php foreach($ceoMemoryProjects as $memoryProject): ?><option value="<?php echo (int)$memoryProject['id']; ?>"><?php echo h(trim((string)$memoryProject['name'])!==''?$memoryProject['name']:'현장정보 확인 필요'); ?></option><?php endforeach; ?></select></label>
 <div style="display:flex;gap:10px;flex-wrap:wrap"><label><strong>적용 시작일</strong><input type="date" name="effective_from" value="<?php echo h(date('Y-m-d')); ?>" style="padding:9px;border:1px solid #cbd5e1;border-radius:9px"></label><label><strong>만료일</strong><input type="date" name="expires_at" style="padding:9px;border:1px solid #cbd5e1;border-radius:9px"></label></div>
 <label><input type="checkbox" name="confirmed" value="1" required> 위 문장, 적용범위와 대상 현장을 확인했습니다.</label><button class="ceo-v2-btn" type="submit">기억 기준 저장 또는 제안</button>
</form>
<div class="ceo-v2-scroll" style="margin-top:15px"><table class="ceo-v2-table"><thead><tr><th>적용범위</th><th>기준 문장</th><th>대상 현장</th><th>적용기간</th><th>버전</th><th>승인상태</th><th>관리</th></tr></thead><tbody><?php if(count($ceoMemories)===0): ?><tr><td colspan="7">저장된 기억 기준이 없습니다.</td></tr><?php else:foreach($ceoMemories as $memory): ?><tr><td><?php echo h(isset($ceoMemoryScopeLabels[$memory['memory_scope']])?$ceoMemoryScopeLabels[$memory['memory_scope']]:'적용범위 확인 필요'); ?></td><td><?php echo nl2br(h($memory['memory_text'])); ?></td><td><?php echo h(trim((string)$memory['project_name'])!==''?$memory['project_name']:'해당 없음'); ?></td><td><?php echo h($memory['effective_from']); ?> ~ <?php echo h($memory['expires_at']!==null?$memory['expires_at']:'만료일 없음'); ?></td><td><?php echo h('버전 '.(int)$memory['version']); ?></td><td><?php echo h(isset($ceoMemoryStatusLabels[$memory['approval_status']])?$ceoMemoryStatusLabels[$memory['approval_status']]:'확인 필요'); ?><?php echo !empty($memory['is_active'])?' · 적용 중':''; ?></td><td>
<?php if($memory['approval_status']==='PENDING'): ?><form method="post" class="ceo-v2-actions"><input type="hidden" name="_csrf" value="<?php echo h($ceoCsrf); ?>"><input type="hidden" name="action" value="review_memory"><input type="hidden" name="memory_id" value="<?php echo (int)$memory['id']; ?>"><input name="reason" placeholder="반려 시 사유" style="padding:8px;border:1px solid #cbd5e1;border-radius:8px"><button class="ceo-v2-btn" name="decision" value="APPROVE">승인</button><button class="ceo-v2-btn secondary" name="decision" value="REJECT">반려</button></form><?php endif; ?>
<?php if(!empty($memory['is_active'])): ?><form method="post" class="ceo-v2-actions" style="margin-top:7px"><input type="hidden" name="_csrf" value="<?php echo h($ceoCsrf); ?>"><input type="hidden" name="action" value="deactivate_memory"><input type="hidden" name="memory_id" value="<?php echo (int)$memory['id']; ?>"><input name="reason" required placeholder="비활성화 사유" style="padding:8px;border:1px solid #cbd5e1;border-radius:8px"><button class="ceo-v2-btn secondary">비활성화</button></form><?php endif; ?>
<details style="margin-top:7px"><summary>새 버전 만들기</summary><form method="post" style="display:grid;gap:6px;margin-top:6px"><input type="hidden" name="_csrf" value="<?php echo h($ceoCsrf); ?>"><input type="hidden" name="action" value="create_memory_version"><input type="hidden" name="memory_id" value="<?php echo (int)$memory['id']; ?>"><textarea name="memory_text" required maxlength="2000" placeholder="수정할 기준 문장"><?php echo h($memory['memory_text']); ?></textarea><div><input type="date" name="effective_from" value="<?php echo h(date('Y-m-d')); ?>"> <input type="date" name="expires_at" value="<?php echo h($memory['expires_at']!==null?$memory['expires_at']:''); ?>"></div><label><input type="checkbox" name="confirmed" value="1" required> 새 문장과 적용기간을 확인했습니다.</label><button class="ceo-v2-btn secondary">새 버전 저장</button></form></details>
<?php if(empty($memory['is_active'])&&in_array($memory['approval_status'],array('APPROVED','RETIRED'),true)): ?><form method="post" class="ceo-v2-actions" style="margin-top:7px"><input type="hidden" name="_csrf" value="<?php echo h($ceoCsrf); ?>"><input type="hidden" name="action" value="reactivate_memory"><input type="hidden" name="memory_id" value="<?php echo (int)$memory['id']; ?>"><input name="reason" required placeholder="재활성화 사유" style="padding:8px;border:1px solid #cbd5e1;border-radius:8px"><button class="ceo-v2-btn secondary">재활성화</button></form><?php endif; ?>
</td></tr><?php endforeach;endif; ?></tbody></table></div><?php endif; ?></section>
