<?php
$ceoChatStatus=$ceoSectionPdo?\App\Services\AiExecutiveChatService::schemaStatus($ceoSectionPdo):array('installed'=>false);
$ceoChatThreads=$ceoSectionPdo&&$ceoV2Ready?\App\Services\AiExecutiveChatService::listV2Threads($ceoSectionPdo,$ceoTargetYm,1,30):array();
$ceoThreadId=isset($_GET['thread_id'])?(int)$_GET['thread_id']:0;if($ceoThreadId<=0&&count($ceoChatThreads))$ceoThreadId=(int)$ceoChatThreads[0]['id'];
$ceoChatThread=$ceoThreadId>0?\App\Services\AiExecutiveChatService::v2Thread($ceoSectionPdo,$ceoThreadId):array();
$ceoChatMessages=!empty($ceoChatThread)?\App\Services\AiExecutiveChatService::messages($ceoSectionPdo,$ceoThreadId,100):array();
?>
<section class="ceo-v2-card"><h3>GPT와 대화</h3><p>선택한 대상 월의 최신 정상 투입비 예측자료를 GPT가 설명합니다. 화면을 열기만 해서는 API를 호출하지 않습니다.</p>
<?php if(!$ceoV2Ready): ?><div class="ceo-v2-note">신규 투입비 예측이 아직 실행되지 않았습니다.<br>자동 파이프라인 또는 개발부서 수동 분석을 먼저 실행해주세요.</div>
<?php elseif(empty($ceoChatStatus['installed'])): ?><div class="ceo-v2-note">GPT 대화 테이블이 아직 설치되지 않았습니다. 개발부서에서 설치해주세요.</div>
<?php else: ?><div class="ceo-v2-note">대화 원본: <?php echo h($ceoSummary['analysis_date']); ?> 정상 투입비 예측 결과</div><div class="ceo-chat-layout"><aside>
 <form method="post"><input type="hidden" name="_csrf" value="<?php echo h($ceoCsrf); ?>"><input type="hidden" name="action" value="new_thread"><input type="hidden" name="target_ym" value="<?php echo h($ceoTargetYm); ?>"><button class="ceo-v2-btn" style="width:100%">새 대화</button></form>
 <div style="margin-top:10px"><?php foreach($ceoChatThreads as $thread): ?><a href="<?php echo h(cpms_ceo_v2_url('gpt_chat',$thread['target_ym'],array('thread_id'=>(int)$thread['id']))); ?>" style="display:block;padding:10px;margin:5px 0;border:1px solid #e2e8f0;border-radius:10px;text-decoration:none;color:#334155"><strong><?php echo h($thread['title']); ?></strong><br><small><?php echo h($thread['target_ym']); ?> · <?php echo h($thread['last_message_at']); ?></small></a><?php endforeach; ?></div>
</aside><div><?php if(empty($ceoChatThread)): ?><div class="ceo-v2-note">새 대화를 만든 후 질문할 수 있습니다.</div><?php else: ?>
 <div class="ceo-chat-messages"><?php foreach($ceoChatMessages as $message): ?><div class="ceo-chat-msg <?php echo $message['role']==='assistant'?'assistant':'user'; ?>"><?php if(!empty($message['data_updated_notice'])): ?><small>분석자료가 갱신되었습니다. 현재 답변은 최신 분석자료 기준입니다.</small><br><?php endif; ?><?php echo nl2br(h($message['message_text'])); ?>
 <?php if($message['role']==='assistant'): $cards=\App\Services\AiExecutiveChatService::evidenceCards($ceoSectionPdo,$message); if(count($cards)): ?><details><summary>PHP 원본 근거 보기</summary><?php foreach($cards as $card): ?><div><?php echo h(isset($card['label'])?$card['label']:'근거'); ?>: <strong><?php echo h(isset($card['display_value'])&&$card['display_value']!==''?$card['display_value']:'-'); ?></strong></div><?php endforeach; ?></details><?php endif;endif; ?></div><?php endforeach; ?></div>
 <form method="post" style="margin-top:10px"><input type="hidden" name="_csrf" value="<?php echo h($ceoCsrf); ?>"><input type="hidden" name="action" value="send_chat"><input type="hidden" name="thread_id" value="<?php echo h((int)$ceoChatThread['id']); ?>"><textarea class="ceo-chat-input" name="question" maxlength="500" placeholder="예: 이번 달 먼저 확인할 현장은 어디야?"></textarea><div class="ceo-v2-actions"><button class="ceo-v2-btn">전송</button><small>최소 <?php echo h((int)$ceoChatStatus['min_seconds']); ?>초 간격 · 시간당 <?php echo h((int)$ceoChatStatus['hourly_limit']); ?>회</small></div></form>
 <form method="post" style="margin-top:8px"><input type="hidden" name="_csrf" value="<?php echo h($ceoCsrf); ?>"><input type="hidden" name="action" value="archive_thread"><input type="hidden" name="thread_id" value="<?php echo h((int)$ceoChatThread['id']); ?>"><button class="ceo-v2-btn secondary">대화방 보관</button></form>
<?php endif; ?></div></div><?php endif; ?><div class="ceo-v2-note">기존 분석자료는 대화 원본으로 사용하지 않습니다. GPT 자유문장에는 수치를 쓰지 않고, 최신 수치는 PHP 근거 카드에서 표시합니다. 개인정보·API 키·시스템 프롬프트·SQL·코드·웹검색 요청은 차단되며 OpenAI 요청은 store=false입니다.</div></section>
