<?php $ceoPipelineStatus=$ceoSectionPdo?\App\Services\AiDailyPipelineService::schemaStatus($ceoSectionPdo):array('installed'=>false,'latest_run'=>array());$ceoLatestPipeline=isset($ceoPipelineStatus['latest_run'])&&is_array($ceoPipelineStatus['latest_run'])?$ceoPipelineStatus['latest_run']:array();$ceoPipelineFailed=isset($ceoLatestPipeline['run_status'])&&in_array($ceoLatestPipeline['run_status'],array('FAILED','PARTIAL'),true); ?>
<?php if($ceoV2Ready&&$ceoPipelineFailed): ?><div class="ceo-v2-note">최근 자동 파이프라인 상태는 <?php echo h($ceoLatestPipeline['run_status']); ?>입니다. 현재 화면에는 <?php echo h($ceoSummary['analysis_date']); ?>의 이전 정상 COST_FORECAST_V2 결과를 표시합니다.</div><?php endif; ?>
<section class="ceo-v2-card"><h3>종합현황</h3><div class="ceo-v2-grid">
 <div class="ceo-v2-kpi"><small>현재 입력 투입비</small><strong><?php echo h(cpms_ceo_v2_money(isset($ceoSummary['current_input_total'])?$ceoSummary['current_input_total']:null)); ?></strong></div>
 <div class="ceo-v2-kpi"><small>미입력 예상금액</small><strong><?php echo h(cpms_ceo_v2_money(isset($ceoSummary['expected_unentered_total'])?$ceoSummary['expected_unentered_total']:null)); ?></strong></div>
 <div class="ceo-v2-kpi"><small>최종 예상 투입비</small><strong><?php echo h(cpms_ceo_v2_money(isset($ceoSummary['final_forecast_total'])?$ceoSummary['final_forecast_total']:null)); ?></strong></div>
 <div class="ceo-v2-kpi"><small>예상범위</small><strong style="font-size:15px"><?php echo h(cpms_ceo_v2_money(isset($ceoSummary['forecast_low_total'])?$ceoSummary['forecast_low_total']:null)); ?> ~ <?php echo h(cpms_ceo_v2_money(isset($ceoSummary['forecast_high_total'])?$ceoSummary['forecast_high_total']:null)); ?></strong></div>
 <div class="ceo-v2-kpi"><small>과다투입 가능 현장</small><strong><?php echo isset($ceoSummary['overinput_count'])?h((int)$ceoSummary['overinput_count'].'개'):'-'; ?></strong></div>
 <div class="ceo-v2-kpi"><small>미입력 가능 현장</small><strong><?php echo isset($ceoSummary['missing_count'])?h((int)$ceoSummary['missing_count'].'개'):'-'; ?></strong></div>
 <div class="ceo-v2-kpi"><small>주요 이상징후</small><strong><?php echo isset($ceoSummary['anomaly_count'])?h((int)$ceoSummary['anomaly_count'].'건'):'-'; ?></strong></div>
 <div class="ceo-v2-kpi"><small>최근 자동분석</small><strong style="font-size:15px"><?php echo h(isset($ceoLatestPipeline['run_status'])?$ceoLatestPipeline['run_status']:'분석 전'); ?></strong><small><?php echo h(isset($ceoLatestPipeline['finished_at'])?$ceoLatestPipeline['finished_at']:''); ?></small></div>
</div></section>
<section class="ceo-v2-card"><h3>오늘 확인할 내용</h3><ul class="ceo-v2-list"><?php if(empty($ceoSummary['available'])): ?><li>최신 자동분석 결과를 먼저 확인해주세요.</li><?php else: ?><?php if(!empty($ceoSummary['overinput_count'])): ?><li>평소보다 높은 투입이 예상되는 <?php echo h((int)$ceoSummary['overinput_count']); ?>개 현장의 비용항목을 확인해주세요.</li><?php endif; ?><?php if(!empty($ceoSummary['missing_count'])): ?><li>추가 입력 가능성이 높은 <?php echo h((int)$ceoSummary['missing_count']); ?>개 현장의 평소 입력시점을 확인해주세요.</li><?php endif; ?><?php if(empty($ceoSummary['overinput_count'])&&empty($ceoSummary['missing_count'])): ?><li>현재 저장자료에서는 우선 확인 경고가 없습니다.</li><?php endif; ?><?php endif; ?></ul><div class="ceo-v2-note">과다투입·미입력 가능성은 확정판정이 아니며 운영자료 확인을 위한 참고 신호입니다.</div></section>
<?php if($ceoSectionDeveloper): ?><section class="ceo-v2-card"><h3>개발 실행</h3><div class="ceo-v2-actions"><form method="post"><input type="hidden" name="_csrf" value="<?php echo h($ceoCsrf); ?>"><input type="hidden" name="action" value="run_pipeline"><button class="ceo-v2-btn">자동 파이프라인 실행</button></form><form method="post"><input type="hidden" name="_csrf" value="<?php echo h($ceoCsrf); ?>"><input type="hidden" name="action" value="force_pipeline"><button class="ceo-v2-btn secondary">같은 날짜 강제 재실행</button></form></div></section><?php endif; ?>
